export const API_KEY = "508f67f602dc40e785119643520f07e7";

export const data = {
  ip: "39.34.149.5",
  continent_code: "AS",
  continent_name: "Asia",
  country_code2: "PK",
  country_code3: "PAK",
  country_name: "Pakistan",
  country_name_official: "Islamic Republic of Pakistan",
  country_capital: "Islamabad",
  state_prov: "Sindh",
  state_code: "PK-SD",
  district: "",
  city: "Karachi",
  zipcode: "75660",
  latitude: "24.86073",
  longitude: "67.00114",
  is_eu: false,
  calling_code: "+92",
  country_tld: ".pk",
  languages: "ur-PK,en-PK,pa,sd,ps,brh",
  country_flag: "https://ipgeolocation.io/static/flags/pk_64.png",
  geoname_id: "7045862",
  isp: "Pakistan Telecommuication company limited",
  connection_type: "",
  organization: "Wancom (Pvt) Ltd.",
  country_emoji: "🇵🇰",
  currency: {
    code: "PKR",
    name: "Pakistan Rupee",
    symbol: "₨",
  },
  time_zone: {
    name: "Asia/Karachi",
    offset: 5,
    offset_with_dst: 5,
    current_time: "2024-08-25 08:25:21.903+0500",
    current_time_unix: 1724556321.903,
    is_dst: false,
    dst_savings: 0,
    dst_exists: false,
    dst_start: "",
    dst_end: "",
  },
};
